### ISSUE TITLE
 "FasterRCNN: 'OlnRPNHead is not in the models registry'"

### ISSUE THREAD

**Issue by CODERED555** [zhenyuw16/UniDetector#32]
请问我如何在registry中注册这个RPNhead呢，因为我是第一次使用不太了解整体训练过程。

**Comment by YH-2023** [comment]
@CODERED555 请问，你知道为什么有的配置文件中把num_classes设置为1，有的设置的却按照数据集的个数设置的？

**Comment by CODERED555** [comment]
> @CODERED555 请问，你知道为什么有的配置文件中把num_classes设置为1，有的设置的却按照数据集的个数设置的？

对不起我也不太知道，我现在整个程序都没有跑通，请问你跑通了吗？

**Comment by YH-2023** [comment]
> > @CODERED555 请问，你知道为什么有的配置文件中把num_classes设置为1，有的设置的却按照数据集的个数设置的？
> 
> 对不起我也不太知道，我现在整个程序都没有跑通，请问你跑通了吗？

我刚看这个

**Comment by YH-2023** [comment]
> 册这个RPNhead呢，因为我是第一次使用不太了解整体训练过程。

你在__init__中导入就可以了
