### ISSUE TITLE
num_classes=1

### ISSUE THREAD

**Issue by YH-2023** [zhenyuw16/UniDetector#33]
为什么有的配置文件中把num_classes设置为1，有的设置的却按照数据集的个数设置的？

**Comment by xiaoyazhu** [comment]
解耦训练的一阶段是为了训练一个通用的目标检测器，不用区分具体是什么类别，所以num_classes=1，而第二阶段是区分每个roi具体是什么类别，所以设置为数据集的类别数。

**Comment by CODERED555** [comment]
> 解耦训练的一阶段是为了训练一个通用的目标检测器，不用区分具体是什么类别，所以num_classes=1，而第二阶段是区分每个roi具体是什么类别，所以设置为数据集的类别数。

请问你成功训练了吗？我是才接触，不是很了解
