### ISSUE TITLE
I have some problems preparing the dataset.

### ISSUE THREAD

**Issue by Suncheng2022** [zhenyuw16/UniDetector#5]
Hi Dear Author, I have some problems preparing the dataset:
1. I am preparing the COCO dataset according to your project directory, but there is no "instances_valminusminival2014.json" file in the origin COCO2014 or COCO2017 dataset. Is this file generated by yourself, and what should I do to generate it?
2. About the LVIS data set, I wonder if your project has preprocessed it when using the LVIS dataset, can I directly go to the lvis official website to download the v1.0 version (because it does not currently provide the v0.5 version) modify the train script and use it directly ?
Thanks in advance！

**Comment by ruifenggong** [comment]
> Hi Dear Author, I have some problems preparing the dataset:
> 
> 1. I am preparing the COCO dataset according to your project directory, but there is no "instances_valminusminival2014.json" file in the origin COCO2014 or COCO2017 dataset. Is this file generated by yourself, and what should I do to generate it?
> 2. About the LVIS data set, I wonder if your project has preprocessed it when using the LVIS dataset, can I directly go to the lvis official website to download the v1.0 version (because it does not currently provide the v0.5 version) modify the train script and use it directly ?
>    Thanks in advance！
去这里下一个annotations_trainval2017.zip，解压过去就有了
https://aistudio.baidu.com/aistudio/datasetdetail/7122

**Comment by Suncheng2022** [comment]
> 1. instances_valminusminival2014.json

没有这个文件—— instances_valminusminival2014.json

**Comment by zhenyuw16** [comment]
instances_valminusminival2014 is actually images that belong to train2017 but are not in train2014. You can create it in this way if you cannot find the annotation file. You can also randomly extract about 35k images from train2017 directly, and the performance will not vary too much.

**Comment by feature-space-move** [comment]
> I just search instances_valminusminival2014.json on Internet and got it in [here](https://github.com/cocodataset/cocoapi/issues/54)
